version: '3.7'
networks:
  elastic:
    name: elastic
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    container_name: es01-test
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
    container_name: kib01-test
    depends_on:
      - elasticsearch
    networks:
      - elastic
